config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :projetos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/projeto.rb
class Projeto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController
  before_action :set_projeto, only: [:show, :edit, :update, :destroy]

  # GET /projetos
  # GET /projetos.json
  def index
    @projetos = Projeto.all
  end

  # GET /projetos/1
  # GET /projetos/1.json
  def show
  end

  # GET /projetos/new
  def new
    @projeto = Projeto.new
  end

  # GET /projetos/1/edit
  def edit
  end

  # POST /projetos
  # POST /projetos.json
  def create
    @projeto = Projeto.new(projeto_params)

    respond_to do |format|
      if @projeto.save
        format.html { redirect_to @projeto, notice: 'Cadastro realizado' }
        format.json { render :show, status: :created, location: @projeto }
      else
        format.html { render :new }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projetos/1
  # PATCH/PUT /projetos/1.json
  def update
    respond_to do |format|
      if @projeto.update(projeto_params)
        format.html { redirect_to @projeto, notice: 'Cadastro Atualizado' }
        format.json { render :show, status: :ok, location: @projeto }
      else
        format.html { render :edit }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projetos/1
  # DELETE /projetos/1.json
  def destroy
    @projeto.destroy
    respond_to do |format|
      format.html { redirect_to projetos_url, notice: 'Cadastro excluído' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projeto
      @projeto = Projeto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projeto_params
      params.require(:projeto).permit(:nome, :matricula, :endereco, :telefone)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projetos/_form.html.erb
<%= form_with(model: projeto, local: true) do |form| %>
  <% if projeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(projeto.errors.count, "error") %> prohibited this projeto from being saved:</h2>

      <ul>
      <% projeto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :matricula %>
    <%= form.text_field :matricula %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_area :endereco %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projetos/edit.html.erb
<h1>Editar Projeto</h1>

<h3><%= render 'form', projeto: @projeto %></h3>

<h2><%= link_to 'Mostrar', @projeto %></h2>

<h2><%= link_to 'Voltar', projetos_path %></h2>

app/views/projetos/index.html.erb
<p id="notice"><%= notice %></p>

<style>
#customers {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

#customers td, #customers th {
    border: 1px solid #ddd;
    padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #4CAF50;
    color: white;
}
</style>
</head>
<table id="customers">
  <tr>
    <th>Nome</th>
    <th>Matricula</th>
    <th>Endereco</th>
    <th>Telefone</th>
    <th></th>
        <th></th>
            <th></th>
  </tr>
   <tbody>
    <% @projetos.each do |projeto| %>
      <tr>
        <td><%= projeto.nome %></td>
        <td><%= projeto.matricula %></td>
        <td><%= projeto.endereco %></td>
        <td><%= projeto.telefone %></td>
        <td><%= link_to 'Mostrar', projeto %></td>
        <td><%= link_to 'Editar', edit_projeto_path(projeto) %></td>
        <td><%= link_to 'Deletar', projeto, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h2><%= link_to 'Novo Cadastro', new_projeto_path %></h2>

app/views/projetos/new.html.erb
<h1>Novo Cadastro</h1>

<%= render 'form', projeto: @projeto %>

<h2><%= link_to 'Voltar', projetos_path %></h2>

app/views/projetos/show.html.erb
<html>
<head>
<style>
#customers {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

#customers td, #customers th {
    border: 1px solid #ddd;
    padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #4CAF50;
    color: white;
}
</style>
</head>
<table id="customers">
  <tr>
    <th>Nome</th>
    <th>Matricula</th>
    <th>Endereco</th>
    <th>Telefone</th>
  </tr>
  <tr>
    <td><%= @projeto.nome %></td>
    <td><%= @projeto.matricula %></td>
    <td><%= @projeto.endereco %></td>
    <td><%= @projeto.telefone %></td>
  </tr>
</table>

<p>

<h2><%= link_to 'Editar', edit_projeto_path(@projeto) %></h2>
<p>
<h2><%= link_to 'Voltar', projetos_path %></h2>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>